    /* write to global pop */
    if (INTERFACE_BC_WEST){//w
         ghostInterface.g_gGhost.X_0[g_idxPopX(ty, tz, 0, bx, by, bz)] = gNode[ 2]; 
         ghostInterface.g_gGhost.X_0[g_idxPopX(ty, tz, 1, bx, by, bz)] = gNode[ 8];
         ghostInterface.g_gGhost.X_0[g_idxPopX(ty, tz, 2, bx, by, bz)] = gNode[10];
         ghostInterface.g_gGhost.X_0[g_idxPopX(ty, tz, 3, bx, by, bz)] = gNode[14];
         ghostInterface.g_gGhost.X_0[g_idxPopX(ty, tz, 4, bx, by, bz)] = gNode[16];
    }if (INTERFACE_BC_EAST){//e
         ghostInterface.g_gGhost.X_1[g_idxPopX(ty, tz, 0, bx, by, bz)] = gNode[ 1];
         ghostInterface.g_gGhost.X_1[g_idxPopX(ty, tz, 1, bx, by, bz)] = gNode[ 7];
         ghostInterface.g_gGhost.X_1[g_idxPopX(ty, tz, 2, bx, by, bz)] = gNode[ 9];
         ghostInterface.g_gGhost.X_1[g_idxPopX(ty, tz, 3, bx, by, bz)] = gNode[13];
         ghostInterface.g_gGhost.X_1[g_idxPopX(ty, tz, 4, bx, by, bz)] = gNode[15];   
    }

    if (INTERFACE_BC_SOUTH){//s          
         ghostInterface.g_gGhost.Y_0[g_idxPopY(tx, tz, 0, bx, by, bz)] = gNode[ 4];
         ghostInterface.g_gGhost.Y_0[g_idxPopY(tx, tz, 1, bx, by, bz)] = gNode[ 8];
         ghostInterface.g_gGhost.Y_0[g_idxPopY(tx, tz, 2, bx, by, bz)] = gNode[12];
         ghostInterface.g_gGhost.Y_0[g_idxPopY(tx, tz, 3, bx, by, bz)] = gNode[13];
         ghostInterface.g_gGhost.Y_0[g_idxPopY(tx, tz, 4, bx, by, bz)] = gNode[18];
    }if (INTERFACE_BC_NORTH){//n
         ghostInterface.g_gGhost.Y_1[g_idxPopY(tx, tz, 0, bx, by, bz)] = gNode[ 3];
         ghostInterface.g_gGhost.Y_1[g_idxPopY(tx, tz, 1, bx, by, bz)] = gNode[ 7];
         ghostInterface.g_gGhost.Y_1[g_idxPopY(tx, tz, 2, bx, by, bz)] = gNode[11];
         ghostInterface.g_gGhost.Y_1[g_idxPopY(tx, tz, 3, bx, by, bz)] = gNode[14];
         ghostInterface.g_gGhost.Y_1[g_idxPopY(tx, tz, 4, bx, by, bz)] = gNode[17];
    }
    
    if (INTERFACE_BC_BACK){ //b
         ghostInterface.g_gGhost.Z_0[g_idxPopZ(tx, ty, 0, bx, by, bz)] = gNode[ 6];
         ghostInterface.g_gGhost.Z_0[g_idxPopZ(tx, ty, 1, bx, by, bz)] = gNode[10];
         ghostInterface.g_gGhost.Z_0[g_idxPopZ(tx, ty, 2, bx, by, bz)] = gNode[12];
         ghostInterface.g_gGhost.Z_0[g_idxPopZ(tx, ty, 3, bx, by, bz)] = gNode[15];
         ghostInterface.g_gGhost.Z_0[g_idxPopZ(tx, ty, 4, bx, by, bz)] = gNode[17];
    }if (INTERFACE_BC_FRONT){
         ghostInterface.g_gGhost.Z_1[g_idxPopZ(tx, ty, 0, bx, by, bz)] = gNode[ 5];
         ghostInterface.g_gGhost.Z_1[g_idxPopZ(tx, ty, 1, bx, by, bz)] = gNode[ 9];
         ghostInterface.g_gGhost.Z_1[g_idxPopZ(tx, ty, 2, bx, by, bz)] = gNode[11];
         ghostInterface.g_gGhost.Z_1[g_idxPopZ(tx, ty, 3, bx, by, bz)] = gNode[16];
         ghostInterface.g_gGhost.Z_1[g_idxPopZ(tx, ty, 4, bx, by, bz)] = gNode[18];
    }